<!--
    Task 1:
    Loop through the contents of the $nav array and create a simple nav object
    Using basic string manipulation, make the content of the A tags contain the
    value of each element in the $nav array and make the HREF attribute a URL
    slug of the that value, for example:

        <a href="/new-orders">New Orders</a>

    (The $nav array variable is already available in this space via the view.)
//-->
